<?xml version="1.0" ?>
<!DOCTYPE SELECT_FROM_StationDescription_SD_LEFT_JOIN_NetworkDescription_ND_ON_SD_parent_oid_ND_oid_RIGHT_JOIN_SensorLocationDescription_SLD_ON_SD_oid_SLD_parent_oid_ [
  <!ELEMENT SELECT_FROM_StationDescription_SD_LEFT_JOIN_NetworkDescription_ND_ON_SD_parent_oid_ND_oid_RIGHT_JOIN_SensorLocationDescription_SLD_ON_SD_oid_SLD_parent_oid_ (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (_oid?,_parent_oid?,_last_modified?,boreholeReference_resourceID?,boreholeReference_used?,creationInfo_agencyID?,creationInfo_agencyURI_resourceID?,creationInfo_agencyURI_used?,creationInfo_author?,creationInfo_authorURI_resourceID?,creationInfo_authorURI_used?,creationInfo_creationTime?,creationInfo_creationTime_ms?,creationInfo_version?,creationInfo_used?,literatureSource_doi?,literatureSource_editor?,literatureSource_firstAuthorFirstName?,literatureSource_firstAuthorLastName?,literatureSource_in_title?,literatureSource_language?,literatureSource_page_from?,literatureSource_page_to?,literatureSource_place?,literatureSource_secondaryAuthors?,literatureSource_title?,literatureSource_tome?,literatureSource_year?,literatureSource_used?,name?,preferredAmplificationFunction_resourceID?,preferredAmplificationFunction_used?,preferredClassicalTravelTimeVelocity_resourceID?,preferredClassicalTravelTimeVelocity_used?,preferredDispersionCurve_resourceID?,preferredDispersionCurve_used?,preferredDominantFrequencyAnalysis_resourceID?,preferredDominantFrequencyAnalysis_used?,preferredHVAnalysis_resourceID?,preferredHVAnalysis_used?,preferredSiteAnalysis_resourceID?,preferredSiteAnalysis_used?,preferredVelocityProfile_resourceID?,preferredVelocityProfile_used?,secondaryStationCode?,siteContact_address?,siteContact_agency?,siteContact_department?,siteContact_email?,siteContact_forename?,siteContact_name?,siteContact_phone?,siteContact_used?,siteMorphology_basinFlagLiteratureSource_doi?,siteMorphology_basinFlagLiteratureSource_editor?,siteMorphology_basinFlagLiteratureSource_firstAuthorFirstName?,siteMorphology_basinFlagLiteratureSource_firstAuthorLastName?,siteMorphology_basinFlagLiteratureSource_in_title?,siteMorphology_basinFlagLiteratureSource_language?,siteMorphology_basinFlagLiteratureSource_page_from?,siteMorphology_basinFlagLiteratureSource_page_to?,siteMorphology_basinFlagLiteratureSource_place?,siteMorphology_basinFlagLiteratureSource_secondaryAuthors?,siteMorphology_basinFlagLiteratureSource_title?,siteMorphology_basinFlagLiteratureSource_tome?,siteMorphology_basinFlagLiteratureSource_year?,siteMorphology_basinFlagLiteratureSource_used?,siteMorphology_bedrockDepth?,siteMorphology_bedrockDepthLiteratureSource_doi?,siteMorphology_bedrockDepthLiteratureSource_editor?,siteMorphology_bedrockDepthLiteratureSource_firstAuthorFirstName?,siteMorphology_bedrockDepthLiteratureSource_firstAuthorLastName?,siteMorphology_bedrockDepthLiteratureSource_in_title?,siteMorphology_bedrockDepthLiteratureSource_language?,siteMorphology_bedrockDepthLiteratureSource_page_from?,siteMorphology_bedrockDepthLiteratureSource_page_to?,siteMorphology_bedrockDepthLiteratureSource_place?,siteMorphology_bedrockDepthLiteratureSource_secondaryAuthors?,siteMorphology_bedrockDepthLiteratureSource_title?,siteMorphology_bedrockDepthLiteratureSource_tome?,siteMorphology_bedrockDepthLiteratureSource_year?,siteMorphology_bedrockDepthLiteratureSource_used?,siteMorphology_creationInfo_agencyID?,siteMorphology_creationInfo_agencyURI_resourceID?,siteMorphology_creationInfo_agencyURI_used?,siteMorphology_creationInfo_author?,siteMorphology_creationInfo_authorURI_resourceID?,siteMorphology_creationInfo_authorURI_used?,siteMorphology_creationInfo_creationTime?,siteMorphology_creationInfo_creationTime_ms?,siteMorphology_creationInfo_version?,siteMorphology_creationInfo_used?,siteMorphology_geologicalSurfaceAge_confidenceLevel?,siteMorphology_geologicalSurfaceAge_lowerUncertainty?,siteMorphology_geologicalSurfaceAge_uncertainty?,siteMorphology_geologicalSurfaceAge_upperUncertainty?,siteMorphology_geologicalSurfaceAge_value?,siteMorphology_geologicalSurfaceAge_used?,siteMorphology_geologicalUnit?,siteMorphology_groundwaterDepth?,siteMorphology_groundwaterDepthLiteratureSource_doi?,siteMorphology_groundwaterDepthLiteratureSource_editor?,siteMorphology_groundwaterDepthLiteratureSource_firstAuthorFname?,siteMorphology_groundwaterDepthLiteratureSource_firstAuthorLname?,siteMorphology_groundwaterDepthLiteratureSource_in_title?,siteMorphology_groundwaterDepthLiteratureSource_language?,siteMorphology_groundwaterDepthLiteratureSource_page_from?,siteMorphology_groundwaterDepthLiteratureSource_page_to?,siteMorphology_groundwaterDepthLiteratureSource_place?,siteMorphology_groundwaterDepthLiteratureSource_secondaryAuthors?,siteMorphology_groundwaterDepthLiteratureSource_title?,siteMorphology_groundwaterDepthLiteratureSource_tome?,siteMorphology_groundwaterDepthLiteratureSource_year?,siteMorphology_groundwaterDepthLiteratureSource_used?,siteMorphology_morphology?,siteMorphology_morphologyLiteratureSource_doi?,siteMorphology_morphologyLiteratureSource_editor?,siteMorphology_morphologyLiteratureSource_firstAuthorFirstName?,siteMorphology_morphologyLiteratureSource_firstAuthorLastName?,siteMorphology_morphologyLiteratureSource_in_title?,siteMorphology_morphologyLiteratureSource_language?,siteMorphology_morphologyLiteratureSource_page_from?,siteMorphology_morphologyLiteratureSource_page_to?,siteMorphology_morphologyLiteratureSource_place?,siteMorphology_morphologyLiteratureSource_secondaryAuthors?,siteMorphology_morphologyLiteratureSource_title?,siteMorphology_morphologyLiteratureSource_tome?,siteMorphology_morphologyLiteratureSource_year?,siteMorphology_morphologyLiteratureSource_used?,siteMorphology_referenceBorehole_resourceID?,siteMorphology_referenceBorehole_used?,siteMorphology_sedimentaryBasinName?,siteMorphology_siteClassDescription?,siteMorphology_siteClassEC8?,siteMorphology_siteClassEC8LiteratureSource_doi?,siteMorphology_siteClassEC8LiteratureSource_editor?,siteMorphology_siteClassEC8LiteratureSource_firstAuthorFirstName?,siteMorphology_siteClassEC8LiteratureSource_firstAuthorLastName?,siteMorphology_siteClassEC8LiteratureSource_in_title?,siteMorphology_siteClassEC8LiteratureSource_language?,siteMorphology_siteClassEC8LiteratureSource_page_from?,siteMorphology_siteClassEC8LiteratureSource_page_to?,siteMorphology_siteClassEC8LiteratureSource_place?,siteMorphology_siteClassEC8LiteratureSource_secondaryAuthors?,siteMorphology_siteClassEC8LiteratureSource_title?,siteMorphology_siteClassEC8LiteratureSource_tome?,siteMorphology_siteClassEC8LiteratureSource_year?,siteMorphology_siteClassEC8LiteratureSource_used?,siteMorphology_siteClassSIA261?,siteMorphology_siteClassSIA261Source_doi?,siteMorphology_siteClassSIA261Source_editor?,siteMorphology_siteClassSIA261Source_firstAuthorFirstName?,siteMorphology_siteClassSIA261Source_firstAuthorLastName?,siteMorphology_siteClassSIA261Source_in_title?,siteMorphology_siteClassSIA261Source_language?,siteMorphology_siteClassSIA261Source_page_from?,siteMorphology_siteClassSIA261Source_page_to?,siteMorphology_siteClassSIA261Source_place?,siteMorphology_siteClassSIA261Source_secondaryAuthors?,siteMorphology_siteClassSIA261Source_title?,siteMorphology_siteClassSIA261Source_tome?,siteMorphology_siteClassSIA261Source_year?,siteMorphology_siteClassSIA261Source_used?,siteMorphology_SurfaceLayerGranularity?,siteMorphology_used?,siteOwnerReference_resourceID?,siteOwnerReference_used?,stationCode?,stationOwnerReference_resourceID?,stationOwnerReference_used?,stationReference_resourceID?,stationReference_used?,_oid?,_parent_oid?,_last_modified?,networkCode?,owner_address?,owner_agency?,owner_department?,owner_email?,owner_forename?,owner_name?,owner_phone?,owner_used?,networkReference_resourceID?,networkReference_used?,_oid?,_parent_oid?,_last_modified?,distanceToBuilding_confidenceLevel?,distanceToBuilding_lowerUncertainty?,distanceToBuilding_uncertainty?,distanceToBuilding_upperUncertainty?,distanceToBuilding_value?,distanceToBuilding_used?,housingClass?,housingDescription?,inBuilding?,storeyCount?,sensorLocationCode?,sensorLocationReference_resourceID?,sensorLocationReference_used?)+>
  <!ELEMENT _oid (#PCDATA)>
  <!ELEMENT _parent_oid (#PCDATA)>
  <!ELEMENT _last_modified (#PCDATA)>
  <!ELEMENT boreholeReference_resourceID (#PCDATA)>
  <!ELEMENT boreholeReference_used (#PCDATA)>
  <!ELEMENT creationInfo_agencyID (#PCDATA)>
  <!ELEMENT creationInfo_agencyURI_resourceID (#PCDATA)>
  <!ELEMENT creationInfo_agencyURI_used (#PCDATA)>
  <!ELEMENT creationInfo_author (#PCDATA)>
  <!ELEMENT creationInfo_authorURI_resourceID (#PCDATA)>
  <!ELEMENT creationInfo_authorURI_used (#PCDATA)>
  <!ELEMENT creationInfo_creationTime (#PCDATA)>
  <!ELEMENT creationInfo_creationTime_ms (#PCDATA)>
  <!ELEMENT creationInfo_version (#PCDATA)>
  <!ELEMENT creationInfo_used (#PCDATA)>
  <!ELEMENT literatureSource_doi (#PCDATA)>
  <!ELEMENT literatureSource_editor (#PCDATA)>
  <!ELEMENT literatureSource_firstAuthorFirstName (#PCDATA)>
  <!ELEMENT literatureSource_firstAuthorLastName (#PCDATA)>
  <!ELEMENT literatureSource_in_title (#PCDATA)>
  <!ELEMENT literatureSource_language (#PCDATA)>
  <!ELEMENT literatureSource_page_from (#PCDATA)>
  <!ELEMENT literatureSource_page_to (#PCDATA)>
  <!ELEMENT literatureSource_place (#PCDATA)>
  <!ELEMENT literatureSource_secondaryAuthors (#PCDATA)>
  <!ELEMENT literatureSource_title (#PCDATA)>
  <!ELEMENT literatureSource_tome (#PCDATA)>
  <!ELEMENT literatureSource_year (#PCDATA)>
  <!ELEMENT literatureSource_used (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT preferredAmplificationFunction_resourceID (#PCDATA)>
  <!ELEMENT preferredAmplificationFunction_used (#PCDATA)>
  <!ELEMENT preferredClassicalTravelTimeVelocity_resourceID (#PCDATA)>
  <!ELEMENT preferredClassicalTravelTimeVelocity_used (#PCDATA)>
  <!ELEMENT preferredDispersionCurve_resourceID (#PCDATA)>
  <!ELEMENT preferredDispersionCurve_used (#PCDATA)>
  <!ELEMENT preferredDominantFrequencyAnalysis_resourceID (#PCDATA)>
  <!ELEMENT preferredDominantFrequencyAnalysis_used (#PCDATA)>
  <!ELEMENT preferredHVAnalysis_resourceID (#PCDATA)>
  <!ELEMENT preferredHVAnalysis_used (#PCDATA)>
  <!ELEMENT preferredSiteAnalysis_resourceID (#PCDATA)>
  <!ELEMENT preferredSiteAnalysis_used (#PCDATA)>
  <!ELEMENT preferredVelocityProfile_resourceID (#PCDATA)>
  <!ELEMENT preferredVelocityProfile_used (#PCDATA)>
  <!ELEMENT secondaryStationCode (#PCDATA)>
  <!ELEMENT siteContact_address (#PCDATA)>
  <!ELEMENT siteContact_agency (#PCDATA)>
  <!ELEMENT siteContact_department (#PCDATA)>
  <!ELEMENT siteContact_email (#PCDATA)>
  <!ELEMENT siteContact_forename (#PCDATA)>
  <!ELEMENT siteContact_name (#PCDATA)>
  <!ELEMENT siteContact_phone (#PCDATA)>
  <!ELEMENT siteContact_used (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_doi (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_editor (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_firstAuthorFirstName (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_firstAuthorLastName (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_in_title (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_language (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_page_from (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_page_to (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_place (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_secondaryAuthors (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_title (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_tome (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_year (#PCDATA)>
  <!ELEMENT siteMorphology_basinFlagLiteratureSource_used (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepth (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_doi (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_editor (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_firstAuthorFirstName (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_firstAuthorLastName (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_in_title (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_language (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_page_from (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_page_to (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_place (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_secondaryAuthors (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_title (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_tome (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_year (#PCDATA)>
  <!ELEMENT siteMorphology_bedrockDepthLiteratureSource_used (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_agencyID (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_agencyURI_resourceID (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_agencyURI_used (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_author (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_authorURI_resourceID (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_authorURI_used (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_creationTime (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_creationTime_ms (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_version (#PCDATA)>
  <!ELEMENT siteMorphology_creationInfo_used (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalSurfaceAge_confidenceLevel (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalSurfaceAge_lowerUncertainty (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalSurfaceAge_uncertainty (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalSurfaceAge_upperUncertainty (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalSurfaceAge_value (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalSurfaceAge_used (#PCDATA)>
  <!ELEMENT siteMorphology_geologicalUnit (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepth (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_doi (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_editor (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_firstAuthorFname (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_firstAuthorLname (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_in_title (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_language (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_page_from (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_page_to (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_place (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_secondaryAuthors (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_title (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_tome (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_year (#PCDATA)>
  <!ELEMENT siteMorphology_groundwaterDepthLiteratureSource_used (#PCDATA)>
  <!ELEMENT siteMorphology_morphology (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_doi (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_editor (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_firstAuthorFirstName (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_firstAuthorLastName (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_in_title (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_language (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_page_from (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_page_to (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_place (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_secondaryAuthors (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_title (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_tome (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_year (#PCDATA)>
  <!ELEMENT siteMorphology_morphologyLiteratureSource_used (#PCDATA)>
  <!ELEMENT siteMorphology_referenceBorehole_resourceID (#PCDATA)>
  <!ELEMENT siteMorphology_referenceBorehole_used (#PCDATA)>
  <!ELEMENT siteMorphology_sedimentaryBasinName (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassDescription (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8 (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_doi (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_editor (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_firstAuthorFirstName (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_firstAuthorLastName (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_in_title (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_language (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_page_from (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_page_to (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_place (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_secondaryAuthors (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_title (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_tome (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_year (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassEC8LiteratureSource_used (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261 (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_doi (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_editor (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_firstAuthorFirstName (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_firstAuthorLastName (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_in_title (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_language (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_page_from (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_page_to (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_place (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_secondaryAuthors (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_title (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_tome (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_year (#PCDATA)>
  <!ELEMENT siteMorphology_siteClassSIA261Source_used (#PCDATA)>
  <!ELEMENT siteMorphology_SurfaceLayerGranularity (#PCDATA)>
  <!ELEMENT siteMorphology_used (#PCDATA)>
  <!ELEMENT siteOwnerReference_resourceID (#PCDATA)>
  <!ELEMENT siteOwnerReference_used (#PCDATA)>
  <!ELEMENT stationCode (#PCDATA)>
  <!ELEMENT stationOwnerReference_resourceID (#PCDATA)>
  <!ELEMENT stationOwnerReference_used (#PCDATA)>
  <!ELEMENT stationReference_resourceID (#PCDATA)>
  <!ELEMENT stationReference_used (#PCDATA)>
  <!ELEMENT _oid (#PCDATA)>
  <!ELEMENT _parent_oid (#PCDATA)>
  <!ELEMENT _last_modified (#PCDATA)>
  <!ELEMENT networkCode (#PCDATA)>
  <!ELEMENT owner_address (#PCDATA)>
  <!ELEMENT owner_agency (#PCDATA)>
  <!ELEMENT owner_department (#PCDATA)>
  <!ELEMENT owner_email (#PCDATA)>
  <!ELEMENT owner_forename (#PCDATA)>
  <!ELEMENT owner_name (#PCDATA)>
  <!ELEMENT owner_phone (#PCDATA)>
  <!ELEMENT owner_used (#PCDATA)>
  <!ELEMENT networkReference_resourceID (#PCDATA)>
  <!ELEMENT networkReference_used (#PCDATA)>
  <!ELEMENT _oid (#PCDATA)>
  <!ELEMENT _parent_oid (#PCDATA)>
  <!ELEMENT _last_modified (#PCDATA)>
  <!ELEMENT distanceToBuilding_confidenceLevel (#PCDATA)>
  <!ELEMENT distanceToBuilding_lowerUncertainty (#PCDATA)>
  <!ELEMENT distanceToBuilding_uncertainty (#PCDATA)>
  <!ELEMENT distanceToBuilding_upperUncertainty (#PCDATA)>
  <!ELEMENT distanceToBuilding_value (#PCDATA)>
  <!ELEMENT distanceToBuilding_used (#PCDATA)>
  <!ELEMENT housingClass (#PCDATA)>
  <!ELEMENT housingDescription (#PCDATA)>
  <!ELEMENT inBuilding (#PCDATA)>
  <!ELEMENT storeyCount (#PCDATA)>
  <!ELEMENT sensorLocationCode (#PCDATA)>
  <!ELEMENT sensorLocationReference_resourceID (#PCDATA)>
  <!ELEMENT sensorLocationReference_used (#PCDATA)>
]>
<SELECT_FROM_StationDescription_SD_LEFT_JOIN_NetworkDescription_ND_ON_SD_parent_oid_ND_oid_RIGHT_JOIN_SensorLocationDescription_SLD_ON_SD_oid_SLD_parent_oid_>
  <DATA_RECORD>
    <_oid>55,976</_oid>
    <_parent_oid>55,910</_parent_oid>
    <_last_modified>2017-02-03 09:10:46</_last_modified>
    <boreholeReference_resourceID></boreholeReference_resourceID>
    <boreholeReference_used>0</boreholeReference_used>
    <creationInfo_agencyID></creationInfo_agencyID>
    <creationInfo_agencyURI_resourceID></creationInfo_agencyURI_resourceID>
    <creationInfo_agencyURI_used>0</creationInfo_agencyURI_used>
    <creationInfo_author></creationInfo_author>
    <creationInfo_authorURI_resourceID></creationInfo_authorURI_resourceID>
    <creationInfo_authorURI_used>0</creationInfo_authorURI_used>
    <creationInfo_creationTime></creationInfo_creationTime>
    <creationInfo_creationTime_ms></creationInfo_creationTime_ms>
    <creationInfo_version></creationInfo_version>
    <creationInfo_used>0</creationInfo_used>
    <literatureSource_doi></literatureSource_doi>
    <literatureSource_editor></literatureSource_editor>
    <literatureSource_firstAuthorFirstName></literatureSource_firstAuthorFirstName>
    <literatureSource_firstAuthorLastName></literatureSource_firstAuthorLastName>
    <literatureSource_in_title></literatureSource_in_title>
    <literatureSource_language></literatureSource_language>
    <literatureSource_page_from></literatureSource_page_from>
    <literatureSource_page_to></literatureSource_page_to>
    <literatureSource_place></literatureSource_place>
    <literatureSource_secondaryAuthors></literatureSource_secondaryAuthors>
    <literatureSource_title></literatureSource_title>
    <literatureSource_tome></literatureSource_tome>
    <literatureSource_year></literatureSource_year>
    <literatureSource_used>0</literatureSource_used>
    <name>Wasen</name>
    <preferredAmplificationFunction_resourceID></preferredAmplificationFunction_resourceID>
    <preferredAmplificationFunction_used>0</preferredAmplificationFunction_used>
    <preferredClassicalTravelTimeVelocity_resourceID>smi:org.orfeus-eu/Analysis/VS30/Z3/20150101/A060A/20150814140000</preferredClassicalTravelTimeVelocity_resourceID>
    <preferredClassicalTravelTimeVelocity_used>0</preferredClassicalTravelTimeVelocity_used>
    <preferredDispersionCurve_resourceID></preferredDispersionCurve_resourceID>
    <preferredDispersionCurve_used>0</preferredDispersionCurve_used>
    <preferredDominantFrequencyAnalysis_resourceID>smi:org.orfeus-eu/Analysis/F0/Z3/20150101/A060A/20150814140000</preferredDominantFrequencyAnalysis_resourceID>
    <preferredDominantFrequencyAnalysis_used>0</preferredDominantFrequencyAnalysis_used>
    <preferredHVAnalysis_resourceID></preferredHVAnalysis_resourceID>
    <preferredHVAnalysis_used>0</preferredHVAnalysis_used>
    <preferredSiteAnalysis_resourceID></preferredSiteAnalysis_resourceID>
    <preferredSiteAnalysis_used>0</preferredSiteAnalysis_used>
    <preferredVelocityProfile_resourceID></preferredVelocityProfile_resourceID>
    <preferredVelocityProfile_used>0</preferredVelocityProfile_used>
    <secondaryStationCode></secondaryStationCode>
    <siteContact_address></siteContact_address>
    <siteContact_agency></siteContact_agency>
    <siteContact_department></siteContact_department>
    <siteContact_email></siteContact_email>
    <siteContact_forename></siteContact_forename>
    <siteContact_name></siteContact_name>
    <siteContact_phone></siteContact_phone>
    <siteContact_used>0</siteContact_used>
    <siteMorphology_basinFlagLiteratureSource_doi></siteMorphology_basinFlagLiteratureSource_doi>
    <siteMorphology_basinFlagLiteratureSource_editor></siteMorphology_basinFlagLiteratureSource_editor>
    <siteMorphology_basinFlagLiteratureSource_firstAuthorFirstName></siteMorphology_basinFlagLiteratureSource_firstAuthorFirstName>
    <siteMorphology_basinFlagLiteratureSource_firstAuthorLastName></siteMorphology_basinFlagLiteratureSource_firstAuthorLastName>
    <siteMorphology_basinFlagLiteratureSource_in_title></siteMorphology_basinFlagLiteratureSource_in_title>
    <siteMorphology_basinFlagLiteratureSource_language></siteMorphology_basinFlagLiteratureSource_language>
    <siteMorphology_basinFlagLiteratureSource_page_from></siteMorphology_basinFlagLiteratureSource_page_from>
    <siteMorphology_basinFlagLiteratureSource_page_to></siteMorphology_basinFlagLiteratureSource_page_to>
    <siteMorphology_basinFlagLiteratureSource_place></siteMorphology_basinFlagLiteratureSource_place>
    <siteMorphology_basinFlagLiteratureSource_secondaryAuthors></siteMorphology_basinFlagLiteratureSource_secondaryAuthors>
    <siteMorphology_basinFlagLiteratureSource_title></siteMorphology_basinFlagLiteratureSource_title>
    <siteMorphology_basinFlagLiteratureSource_tome></siteMorphology_basinFlagLiteratureSource_tome>
    <siteMorphology_basinFlagLiteratureSource_year></siteMorphology_basinFlagLiteratureSource_year>
    <siteMorphology_basinFlagLiteratureSource_used>0</siteMorphology_basinFlagLiteratureSource_used>
    <siteMorphology_bedrockDepth></siteMorphology_bedrockDepth>
    <siteMorphology_bedrockDepthLiteratureSource_doi></siteMorphology_bedrockDepthLiteratureSource_doi>
    <siteMorphology_bedrockDepthLiteratureSource_editor></siteMorphology_bedrockDepthLiteratureSource_editor>
    <siteMorphology_bedrockDepthLiteratureSource_firstAuthorFirstName></siteMorphology_bedrockDepthLiteratureSource_firstAuthorFirstName>
    <siteMorphology_bedrockDepthLiteratureSource_firstAuthorLastName></siteMorphology_bedrockDepthLiteratureSource_firstAuthorLastName>
    <siteMorphology_bedrockDepthLiteratureSource_in_title></siteMorphology_bedrockDepthLiteratureSource_in_title>
    <siteMorphology_bedrockDepthLiteratureSource_language></siteMorphology_bedrockDepthLiteratureSource_language>
    <siteMorphology_bedrockDepthLiteratureSource_page_from></siteMorphology_bedrockDepthLiteratureSource_page_from>
    <siteMorphology_bedrockDepthLiteratureSource_page_to></siteMorphology_bedrockDepthLiteratureSource_page_to>
    <siteMorphology_bedrockDepthLiteratureSource_place></siteMorphology_bedrockDepthLiteratureSource_place>
    <siteMorphology_bedrockDepthLiteratureSource_secondaryAuthors></siteMorphology_bedrockDepthLiteratureSource_secondaryAuthors>
    <siteMorphology_bedrockDepthLiteratureSource_title></siteMorphology_bedrockDepthLiteratureSource_title>
    <siteMorphology_bedrockDepthLiteratureSource_tome></siteMorphology_bedrockDepthLiteratureSource_tome>
    <siteMorphology_bedrockDepthLiteratureSource_year></siteMorphology_bedrockDepthLiteratureSource_year>
    <siteMorphology_bedrockDepthLiteratureSource_used>0</siteMorphology_bedrockDepthLiteratureSource_used>
    <siteMorphology_creationInfo_agencyID></siteMorphology_creationInfo_agencyID>
    <siteMorphology_creationInfo_agencyURI_resourceID></siteMorphology_creationInfo_agencyURI_resourceID>
    <siteMorphology_creationInfo_agencyURI_used>0</siteMorphology_creationInfo_agencyURI_used>
    <siteMorphology_creationInfo_author></siteMorphology_creationInfo_author>
    <siteMorphology_creationInfo_authorURI_resourceID></siteMorphology_creationInfo_authorURI_resourceID>
    <siteMorphology_creationInfo_authorURI_used>0</siteMorphology_creationInfo_authorURI_used>
    <siteMorphology_creationInfo_creationTime></siteMorphology_creationInfo_creationTime>
    <siteMorphology_creationInfo_creationTime_ms></siteMorphology_creationInfo_creationTime_ms>
    <siteMorphology_creationInfo_version></siteMorphology_creationInfo_version>
    <siteMorphology_creationInfo_used>0</siteMorphology_creationInfo_used>
    <siteMorphology_geologicalSurfaceAge_confidenceLevel></siteMorphology_geologicalSurfaceAge_confidenceLevel>
    <siteMorphology_geologicalSurfaceAge_lowerUncertainty></siteMorphology_geologicalSurfaceAge_lowerUncertainty>
    <siteMorphology_geologicalSurfaceAge_uncertainty></siteMorphology_geologicalSurfaceAge_uncertainty>
    <siteMorphology_geologicalSurfaceAge_upperUncertainty></siteMorphology_geologicalSurfaceAge_upperUncertainty>
    <siteMorphology_geologicalSurfaceAge_value></siteMorphology_geologicalSurfaceAge_value>
    <siteMorphology_geologicalSurfaceAge_used>0</siteMorphology_geologicalSurfaceAge_used>
    <siteMorphology_geologicalUnit>Conglomerate</siteMorphology_geologicalUnit>
    <siteMorphology_groundwaterDepth></siteMorphology_groundwaterDepth>
    <siteMorphology_groundwaterDepthLiteratureSource_doi></siteMorphology_groundwaterDepthLiteratureSource_doi>
    <siteMorphology_groundwaterDepthLiteratureSource_editor></siteMorphology_groundwaterDepthLiteratureSource_editor>
    <siteMorphology_groundwaterDepthLiteratureSource_firstAuthorFname></siteMorphology_groundwaterDepthLiteratureSource_firstAuthorFname>
    <siteMorphology_groundwaterDepthLiteratureSource_firstAuthorLname></siteMorphology_groundwaterDepthLiteratureSource_firstAuthorLname>
    <siteMorphology_groundwaterDepthLiteratureSource_in_title></siteMorphology_groundwaterDepthLiteratureSource_in_title>
    <siteMorphology_groundwaterDepthLiteratureSource_language></siteMorphology_groundwaterDepthLiteratureSource_language>
    <siteMorphology_groundwaterDepthLiteratureSource_page_from></siteMorphology_groundwaterDepthLiteratureSource_page_from>
    <siteMorphology_groundwaterDepthLiteratureSource_page_to></siteMorphology_groundwaterDepthLiteratureSource_page_to>
    <siteMorphology_groundwaterDepthLiteratureSource_place></siteMorphology_groundwaterDepthLiteratureSource_place>