<?xml version="1.0" ?>
<!DOCTYPE SELECT_FROM_StationCharacterizationFileResource [
  <!ELEMENT SELECT_FROM_StationCharacterizationFileResource (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (_oid?,_parent_oid?,_last_modified?,file_class?,file_creationInfo_agencyID?,file_creationInfo_agencyURI_resourceID?,file_creationInfo_agencyURI_used?,file_creationInfo_author?,file_creationInfo_authorURI_resourceID?,file_creationInfo_authorURI_used?,file_creationInfo_creationTime?,file_creationInfo_creationTime_ms?,file_creationInfo_version?,file_creationInfo_used?,file_description?,file_filename?,file_type?,file_url?)+>
  <!ELEMENT _oid (#PCDATA)>
  <!ELEMENT _parent_oid (#PCDATA)>
  <!ELEMENT _last_modified (#PCDATA)>
  <!ELEMENT file_class (#PCDATA)>
  <!ELEMENT file_creationInfo_agencyID (#PCDATA)>
  <!ELEMENT file_creationInfo_agencyURI_resourceID (#PCDATA)>
  <!ELEMENT file_creationInfo_agencyURI_used (#PCDATA)>
  <!ELEMENT file_creationInfo_author (#PCDATA)>
  <!ELEMENT file_creationInfo_authorURI_resourceID (#PCDATA)>
  <!ELEMENT file_creationInfo_authorURI_used (#PCDATA)>
  <!ELEMENT file_creationInfo_creationTime (#PCDATA)>
  <!ELEMENT file_creationInfo_creationTime_ms (#PCDATA)>
  <!ELEMENT file_creationInfo_version (#PCDATA)>
  <!ELEMENT file_creationInfo_used (#PCDATA)>
  <!ELEMENT file_description (#PCDATA)>
  <!ELEMENT file_filename (#PCDATA)>
  <!ELEMENT file_type (#PCDATA)>
  <!ELEMENT file_url (#PCDATA)>
]>
<SELECT_FROM_StationCharacterizationFileResource>
  <DATA_RECORD>
    <_oid>82,918</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 11:28:46</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Final installation</file_description>
    <file_filename>IMG_0321.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A001A/IMG_0321.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,920</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 11:29:28</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Shelter from outside</file_description>
    <file_filename>IMG_2916.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A001A/IMG_2916.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,922</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 11:30:49</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Power supply with solar panel</file_description>
    <file_filename>IMG_0309.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A001A/IMG_0309.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,924</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 11:31:37</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Second solar panel installed later</file_description>
    <file_filename>IMG_3063.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A001A/IMG_3063.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,927</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 12:25:43</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Building from outside</file_description>
    <file_filename>IMG_2827.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A002A/IMG_2827.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,929</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 12:26:12</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor</file_description>
    <file_filename>IMG_3189.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A002A/IMG_3189.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,932</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 12:38:50</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Building outside</file_description>
    <file_filename>IMG_2913.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A003A/IMG_2913.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,934</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 12:39:08</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Building inside</file_description>
    <file_filename>IMG_2912.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A003A/IMG_2912.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,936</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 12:39:33</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor</file_description>
    <file_filename>IMG_2891.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A003A/IMG_2891.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,939</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:32:45</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Castle outside</file_description>
    <file_filename>A004A.jpg</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A004A/A004A.jpg</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,941</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:33:25</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor and data logger</file_description>
    <file_filename>IMG_2900.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A004A/IMG_2900.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,946</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:40:59</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Hut outside</file_description>
    <file_filename>IMG_0071.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A005A/IMG_0071.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,948</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:41:17</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor thermal cover</file_description>
    <file_filename>P1130539.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A005A/P1130539.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,950</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:41:47</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor and data logger</file_description>
    <file_filename>P1130544.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A005A/P1130544.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,953</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:46:15</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Outside</file_description>
    <file_filename>IMG_0749.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A006A/IMG_0749.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,955</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:47:15</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor on concrete socket</file_description>
    <file_filename>IMG_0744.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A006A/IMG_0744.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,957</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 13:48:03</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Data logger and entrance</file_description>
    <file_filename>IMG_0745.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A006A/IMG_0745.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,960</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:08:55</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Castle entrance outside</file_description>
    <file_filename>IMG_1530.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A007A/IMG_1530.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,962</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:09:43</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor setup</file_description>
    <file_filename>IMG_1522.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A007A/IMG_1522.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,964</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:10:11</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor final installation</file_description>
    <file_filename>IMG_1527.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A007A/IMG_1527.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,967</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:18:41</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Final installation</file_description>
    <file_filename>IMG_0738.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A008A/IMG_0738.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,969</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:19:08</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor on concrete base</file_description>
    <file_filename>IMG_0722.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A008A/IMG_0722.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,971</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:19:49</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor in wooden hut (concrete tower was removed)</file_description>
    <file_filename>IMG_0147.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A008A/IMG_0147.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,974</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:33:46</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Outside</file_description>
    <file_filename>IMG_0109.jpg</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A009A/IMG_0109.jpg</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,976</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:34:27</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor closeup</file_description>
    <file_filename>IMG_0110.JPG</file_filename>
    <file_type>image/jpeg</file_type>
    <file_url>/stationbook-files/Z3/A009A/IMG_0110.JPG</file_url>
  </DATA_RECORD>
  <DATA_RECORD>
    <_oid>82,978</_oid>
    <_parent_oid>1</_parent_oid>
    <_last_modified>2016-05-17 15:34:52</_last_modified>
    <file_class>picture</file_class>
    <file_creationInfo_agencyID></file_creationInfo_agencyID>
    <file_creationInfo_agencyURI_resourceID></file_creationInfo_agencyURI_resourceID>
    <file_creationInfo_agencyURI_used>0</file_creationInfo_agencyURI_used>
    <file_creationInfo_author></file_creationInfo_author>
    <file_creationInfo_authorURI_resourceID></file_creationInfo_authorURI_resourceID>
    <file_creationInfo_authorURI_used>0</file_creationInfo_authorURI_used>
    <file_creationInfo_creationTime></file_creationInfo_creationTime>
    <file_creationInfo_creationTime_ms></file_creationInfo_creationTime_ms>
    <file_creationInfo_version></file_creationInfo_version>
    <file_creationInfo_used>0</file_creationInfo_used>
    <file_description>Sensor shelter</file_description>
    <file_filename>IMG_0119.JPG</file_filename>
    <file_type>image/jpeg</file_type>